# Generated by Django 5.2.6 on 2025-09-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, help_text="Укажите chat ID в Телеграм", null=True, verbose_name="Chat ID"
            ),
        ),
    ]
