# Generated by Django 5.2.6 on 2025-09-08 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        ("places", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.TimeField(help_text="Введите время выполнения привычки.", verbose_name="Время")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, приятна привычка или нет.",
                        verbose_name="Признак приятности",
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(default=1, help_text="Выберите периодичность.", verbose_name="Периодичность"),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите вознаграждение за выполнение привычки.",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        help_text="Укажите время, необходимое для выполнения привычки (в секундах).",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="Укажите хотите поделиться или нет.", verbose_name="Признак публичности"
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        help_text="Выберите действие.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to="actions.action",
                        verbose_name="Действие",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Выберите Владельца.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        help_text="Выберите место.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to="places.place",
                        verbose_name="Место",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
    ]
